import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-bg-gray">
        <div className="bg-slate-200 max-w-7xl mx-auto shadow-xl border-1 min-h-[52rem] border-gray-600">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
